In [2]:
import os
print(os.listdir('/'))

['lib32', 'proc', 'mnt', 'libx32', 'sys', 'root', 'srv', 'etc', 'tmp', 'sbin', 'opt', 'media', 'run', 'dev', 'var', 'home', 'usr', 'bin', 'lib', 'lib64', 'boot', 'startup_funding.csv', 'kaggle', '.dockerenv', 'tools', 'datalab', 'content', 'python-apt', 'python-apt.tar.xz']

In [5]:
import pandas as pd
df  = pd.read_csv("/startup_funding.csv")

In [8]:
df.shape
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [10]:
df['Date dd/mm/yyyy'].dtype

dtype('O')

In [15]:
df['Date dd/mm/yyyy'] = pd.to_datetime(df['Date dd/mm/yyyy'], dayfirst=True , errors='coerce')

In [16]:
df['Date dd/mm/yyyy'].dtype

dtype('<M8[ns]')

In [17]:
df['Date dd/mm/yyyy'].isnull().sum()

np.int64(8)

In [18]:
df[df['Date dd/mm/yyyy'].isnull()]

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
192,193,NaT,Loan Tap,Consumer Internet,Online Lending Platform For Salaried Professio...,Mumbai,"Shunwei Capital, Tuscan Ventures, Ashish Goenk...",Private Equity,"62,50,000",NaN
2571,2572,NaT,HandyHome,Hyperlocal Electronics repair Service,NaN,Mumbai,"Bessemer Ventures, Kae Capital",Seed Funding,"6,30,000",NaN
2606,2607,NaT,\\xc2\\xa0Infinity Assurance,\\xc2\\xa0Warranty Programs Service Administra...,NaN,\\xc2\\xa0New Delhi,\\xc2\\xa0Indian Angel Network,Seed Funding,"\\xc2\\xa0600,000",NaN
2775,2776,NaT,Mobiefit,Mobile Fitness App,NaN,Goa,Prototyze,Seed Funding,NaN,NaN
2776,2777,NaT,Plancess,Online Education Platform,NaN,Mumbai,"Rajendra Gogri,\\xc2\\xa0 Chandrakant Gogri",Seed Funding,"20,00,000",NaN
2831,2832,NaT,The Porter,Logistics Tech,NaN,Mumbai,Kae Capital,Seed Funding,"5,00,000",NaN
3011,3012,NaT,Wishberry,NaN,NaN,NaN,"Rajan Anandan, Shankar Mahadevan, Deep Kalra &...",Seed Funding,"6,50,000",NaN
3029,3030,NaT,Corporate360,NaN,NaN,NaN,Group of Angel Investors,Seed Funding,"2,00,000",NaN

In [19]:
df =df.dropna(subset =['Date dd/mm/yyyy'])

In [22]:
df['Date dd/mm/yyyy'].isnull().sum()

np.int64(0)

In [21]:
df.shape

(3036, 10)

In [23]:
df['Amount in USD'].dtype

dtype('O')

In [24]:
df['Amount in USD'] = df['Amount in USD'].str.replace(',' , '')

In [25]:
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000,NaN
1,2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394,NaN
2,3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860,NaN
3,4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000,NaN
4,5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000,NaN

In [27]:
df['Amount in USD'] = pd.to_numeric(df['Amount in USD'] , errors='coerce' )

In [28]:
df['Amount in USD'].isnull().sum()

np.int64(977)

In [29]:
df[df['Amount in USD'].isnull()]

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
20,21,2019-11-17,Burger Singh,Food and Beverage,Indian Burger Brand,Gurgaon,RB Investments,Venture,NaN,NaN
34,35,2019-10-21,The Man Company,Consumer Goods,Beauty and Grooming,Gurgaon,Ayushmann Khurana,Corporate Round,NaN,NaN
58,59,2019-08-19,Mishry Reviews,Services,Product Review,Gurgaon,Vir Sanghvi,Series A,NaN,NaN
89,90,2019-05-06,Ola Electric,Transport,Cabs,Bengaluru,Tata Sons,Series A,NaN,NaN
91,92,2019-05-05,StyleDotMe,E-commerce,Fashion and Shopping,Delhi,Indian Angel Network and other angel investors...,Bridge Round,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3027,3028,2015-05-21,Knit,NaN,NaN,NaN,"Rohit Jain, Amit Rambhia & Others",Seed Funding,NaN,NaN
3030,3031,2015-01-22,Freshmonk,NaN,NaN,NaN,"August Capital Partners, Michael Blakey",Seed Funding,NaN,NaN
3031,3032,2015-01-22,Englishleap.com,NaN,NaN,NaN,ANALEC,Private Equity,NaN,Majority Stake
3035,3036,2015-01-24,Impartus,NaN,NaN,NaN,Kaizen Private Equity,Private Equity,NaN,Series A
3042,3043,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"

In [30]:
df.isnull().sum()

Sr No                   0
Date dd/mm/yyyy         0
Startup Name            0
Industry Vertical     169
SubVertical           929
City  Location        178
Investors Name         24
InvestmentnType         4
Amount in USD         977
Remarks              2617
dtype: int64

In [31]:
df = df.drop(columns=['Remarks'])

In [32]:
df.shape

(3036, 9)

In [35]:
df = df.dropna(subset = ['InvestmentnType'])

In [36]:
df.shape

(3032, 9)

In [42]:
df['Investors Name'] = df['Investors Name'].fillna('Unknown')

/tmp/ipykernel_1238/871457619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Investors Name'] = df['Investors Name'].fillna('Unknown')

In [38]:
df.isnull().sum()

Sr No                  0
Date dd/mm/yyyy        0
Startup Name           0
Industry Vertical    169
SubVertical          929
City  Location       178
Investors Name         0
InvestmentnType        0
Amount in USD        976
dtype: int64

In [43]:
df['Industry Vertical'] = df['Industry Vertical'].fillna('Unknown')
df['City  Location'] = df['City  Location'].fillna('Unknown')

/tmp/ipykernel_1238/1873340071.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Industry Vertical'] = df['Industry Vertical'].fillna('Unknown')
/tmp/ipykernel_1238/1873340071.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City  Location'] = df['City  Location'].fillna('Unknown')

In [45]:
df = df.drop(columns= ['SubVertical'])

In [46]:
df.isnull().sum()

Sr No                  0
Date dd/mm/yyyy        0
Startup Name           0
Industry Vertical      0
City  Location         0
Investors Name         0
InvestmentnType        0
Amount in USD        976
dtype: int64